### ISSUE TITLE
read_annot.tsv gene_novelty:Other

### ISSUE THREAD

**Issue by ashokpatowary** [mortazavilab/TALON#56]
Hi @dewyman 

What I understand in the read_annot.tsv file there can be three catagory i.e known, intergenic and antisense. But in my dataset I am getting an additional type "Other". I do member you did it last year when I reach out to you. But because of this category "Other"  I failed to run abundance script. So, should I modify the read_annot.tsv file removing all the "Other" gene_novelty category. Bellow is an example.

30639 110636 ENSG00000239148.1 ENST00000459141.1 U8 U8.22-201 Other Other
30764 230075 ENSG00000272507.1 TALONT000230075 U6 TALONT000230075 Other Genomic
30764 230076 ENSG00000272507.1 TALONT000230076 U6 TALONT000230076 Other NIC
30764 230077 ENSG00000272507.1 TALONT000230077 U6 TALONT000230077 Other ISM
31280 230589 ENSG00000238732.1 TALONT000230589 snoU13 TALONT000230589 Other Genomic

**Comment by dewyman** [comment]
Hi Ashok,

You are correct- the 'Other' category is a patch I put in to resolve issue #47 last year. It covers cases where the novelty type of a gene or transcript in your reference GTF was listed as something other than 'KNOWN'. Since the abundance script runs on the database rather than the read_annot file, editing the read_annot file unfortunately won't help with this. 

One way to address this would be to edit your input GTF file to remove the gene_status and transcript_status labels. This would make TALON default the GTF models to known. Another option would be to remove entries from the GTF that have a novel gene_status or transcript_status prior to the database init.

It is possible that an abundance script patch would also be a useful part of the solution to this problem. Would you mind sending more information about the error you are getting?

Best,
Dana

**Comment by ashokpatowary** [comment]
Hi @dewyman 

My bad. Since I was trying to under the error on the in the read_annot.tsv file; I just flow with it and confuse it with database file. Bellow is the error. I think it will be helpful if there can be an abundance script patch. Also, I am having a not so important query. Is there any way to generate abundance for all the transcript if I run it on a single sample? What I understand from the description that in case of only one sample abundance will be generated only for known category.

Thanks

Warning: Could not locate novelty type for gene 750
Traceback (most recent call last):
  File "/u/home/a/ashokpat/.local/bin/talon_abundance", line 11, in <module>
    load_entry_point('talon==5.0', 'console_scripts', 'talon_abundance')()
  File "/u/home/a/ashokpat/.local/lib/python3.7/site-packages/talon/post/create_abundance_file_from_database.py", line 469, in main
    write_abundance_file(abundances, colnames, prefix, n_places, datasets, novelty_type, transcript_lengths, outfile)
  File "/u/home/a/ashokpat/.local/lib/python3.7/site-packages/talon/post/create_abundance_file_from_database.py", line 234, in write_abundance_file
    [ curr_novelty[x] for x in novelty_type_cols] + \
  File "/u/home/a/ashokpat/.local/lib/python3.7/site-packages/talon/post/create_abundance_file_from_database.py", line 234, in <listcomp>
    [ curr_novelty[x] for x in novelty_type_cols] + \
KeyError: 'gene_novelty'
Warning: Could not locate novelty type for gene 750
Traceback (most recent call last):
  File "/u/home/a/ashokpat/.local/bin/talon_abundance", line 11, in <module>
    load_entry_point('talon==5.0', 'console_scripts', 'talon_abundance')()
  File "/u/home/a/ashokpat/.local/lib/python3.7/site-packages/talon/post/create_abundance_file_from_database.py", line 469, in main
    write_abundance_file(abundances, colnames, prefix, n_places, datasets, novelty_type, transcript_lengths, outfile)
  File "/u/home/a/ashokpat/.local/lib/python3.7/site-packages/talon/post/create_abundance_file_from_database.py", line 234, in write_abundance_file
    [ curr_novelty[x] for x in novelty_type_cols] + \
  File "/u/home/a/ashokpat/.local/lib/python3.7/site-packages/talon/post/create_abundance_file_from_database.py", line 234, in <listcomp>
    [ curr_novelty[x] for x in novelty_type_cols] + \
KeyError: 'gene_novelty'

**Comment by fairliereese** [comment]
To answer your question about generating an abundance matrix for all transcripts in your sample, all you have to do is run the talon_abundance script without the --whitelist option. This will provide you with an unfiltered abundance file that should include each of the transcript counts.

**Comment by ashokpatowary** [comment]
@fairliereese Thanks. Yes UI managed to  get it. Thanks again.

**Comment by fairliereese** [comment]
Were you able to get the abundance script running? We want to make sure that we are supporting all of our user's input data types.

**Comment by ashokpatowary** [comment]
@fairliereese I modified the input gtf file as suggested by @dewyman and the abundance file generated. I haver not looked into the data, but for users using gencod v33 (which I am using) one need to modify the gtf.

**Comment by fairliereese** [comment]
Could you please send me the gtf you're trying to work with? I'm having trouble tracking down the issue with the GENCODE v33 gtf. freese@uci.edu

**Comment by ashokpatowary** [comment]
@fairliereese I will send it latter tonight. Thanks

**Comment by ashokpatowary** [comment]
@fairliereese should I close this issue or you are working on it? My problem has been solved by modifying the input reference gtf file. Thanks

**Comment by fairliereese** [comment]
I would still like to take a stab at fixing this internally as we should be able to run TALON with GENCODE GTFs at the very least so go ahead and leave it open :)

**Comment by Seamonkey28** [comment]
Hi,

I am coming up with the same error (KeyError: 'gene_novelty') when running talon_annotate. I am using the gencode.v40lift37.annotation.gtf. @dewyman suggested editing the gtf file to remove all 'other' categories. I'm not quite sure how to do this...and that means I will have to run all the previous steps right, starting from creating the database.

**Comment by fairliereese** [comment]
Unfortunately yes, this does mean you'd need to reinitialize your database. But I can provide you some code to remove the GTF tags that are confusing TALON (as mentioned above, the `gene_status` and `transcript_status` tags. 

```python
import pyranges as pr
df = pr.read_gtf('gencode.v40lift37.annotation.gtf', as_df=True)
df.drop(['transcript_status', 'gene_status'], axis=1, inplace=True)
df =pr.PyRanges(df)
df.to_gtf('gencode.v40lift37.annotation_no_status_tags.gtf')
```

**Comment by MustafaElshani** [comment]
Even though I am using gencode.47 I m still getting the error

```
Traceback (most recent call last):
  File "/mnt/shared/scratch/melshani/apps/conda/envs/talon_lapa/bin/talon_abundance", line 8, in <module>
    sys.exit(main())
  File "/mnt/shared/scratch/melshani/apps/conda/envs/talon_lapa/lib/python3.7/site-packages/talon/post/create_abundance_file_from_database.py", line 496, in main
    write_abundance_file(abundances, colnames, prefix, n_places, datasets, novelty_type, transcript_lengths, outfile)
  File "/mnt/shared/scratch/melshani/apps/conda/envs/talon_lapa/lib/python3.7/site-packages/talon/post/create_abundance_file_from_database.py", line 263, in write_abundance_file
    + transcript[first_dataset_index:]
  File "/mnt/shared/scratch/melshani/apps/conda/envs/talon_lapa/lib/python3.7/site-packages/talon/post/create_abundance_file_from_database.py", line 262, in <listcomp>
    + [curr_novelty[x] for x in novelty_type_cols]
KeyError: 'gene_novelty'
```
 gtf should not have any transcript_status as per genecode 
```
e The 'gene_status' and 'transcript_status' attributes were removed after releases 25 (human) and M11 (mouse).
```

talon_abundance usage was 
```
talon_abundance \
      --db $db_path \
      --whitelist ./analysis/TALON_LAPA/TALON/${sample_prefix}_TALON_filtered_transcripts.csv \
      -a gencode.v47_annot \
      --build gencode.v47 \
      --o ./analysis/TALON_LAPA/TALON/${sample_prefix}
```
Any help appreciated
